"""Mini Grid-Mind reproduction package."""

from .anti_hallucination import (
    ANTI_FABRICATION_PROMPT_RULES,
    CIAReadinessDecision,
    GROUNDING_CAPABLE_TOOLS,
    GROUNDING_WARNING,
    CapacityRouteDecision,
    GroundingValidation,
    NumericClaim,
    ToolCallPolicyDecision,
    detect_capacity_route,
    detect_cia_readiness,
    find_numeric_claims,
    handle_forced_capacity_routing,
    has_grounding_credit,
    validate_tool_call_policy,
    validate_grounding,
)
from .agent import (
    AgentConfig,
    AgentLoopError,
    AgentTurnResult,
    GridMindAgent,
    ToolExecutionRecord,
    summarize_capacity_result,
)
from .capacity import CapacitySearchRunner
from .cia import ConnectionRequest, SteadyStateCIARunner
from .contingency import ContingencyRunner
from .experiments import (
    ExperimentExpectation,
    ExperimentResult,
    ExperimentRunner,
    ExperimentScenario,
    ExperimentSuiteResult,
    ExpectationResult,
    default_experiment_scenarios,
    evaluate_expectations,
    filter_scenarios,
)
from .llm import (
    DEFAULT_LOCAL_MODEL,
    DEFAULT_QWEN_MODEL,
    DEFAULT_VLLM_BASE_URL,
    ChatCompletion,
    Completion,
    LLMClientError,
    ToolCall,
    VLLMConfig,
    VLLMOpenAIClient,
    parse_chat_completion_response,
    parse_completion_response,
    parse_openai_function_call,
    parse_openai_tool_calls,
    parse_tool_calls_from_text,
    remove_tool_call_blocks,
    render_qwen_chatml,
    strip_qwen_thinking,
    tool_result_message,
)
from .m1_benchmark import (
    M1BenchmarkCheckResult,
    M1BenchmarkResult,
    M1BenchmarkRunner,
    M1BenchmarkScenario,
    M1BenchmarkSuiteResult,
    M1OracleComparison,
    default_m1_benchmark_scenarios,
    evaluate_m1_result,
    filter_m1_scenarios,
    run_m1_oracles,
)
from .memory import MEMORY_CONTEXT_CAVEAT, StudyMemoryRecord, StudyMemoryStore
from .observations import build_tool_observation, tool_observation_payload
from .prompting import (
    DEFAULT_AGENT_IDENTITY,
    PromptBuildResult,
    PromptContextHints,
    build_chat_messages,
    build_gridmind_prompt,
    extract_context_hints,
    select_relevant_memory,
)
from .reporting import (
    REPORTABLE_TOOLS,
    DeterministicReport,
    build_deterministic_report,
    report_text_or_original,
)
from .solver import CaseInfo, GridSolver, PandaPowerSolver, PowerFlowError, SolverDependencyError
from .tools import BackendDefinition, ToolDefinition, ToolRegistry, ToolRegistryError
from .violations import (
    InspectionReport,
    LimitProfile,
    Violation,
    ViolationInspector,
    profile_from_name,
)

__all__ = [
    "ANTI_FABRICATION_PROMPT_RULES",
    "AgentConfig",
    "AgentLoopError",
    "AgentTurnResult",
    "CaseInfo",
    "CapacitySearchRunner",
    "CapacityRouteDecision",
    "CIAReadinessDecision",
    "ChatCompletion",
    "ConnectionRequest",
    "ContingencyRunner",
    "Completion",
    "DEFAULT_AGENT_IDENTITY",
    "DEFAULT_LOCAL_MODEL",
    "DEFAULT_QWEN_MODEL",
    "DEFAULT_VLLM_BASE_URL",
    "DeterministicReport",
    "ExperimentExpectation",
    "ExperimentResult",
    "ExperimentRunner",
    "ExperimentScenario",
    "ExperimentSuiteResult",
    "ExpectationResult",
    "GROUNDING_CAPABLE_TOOLS",
    "GROUNDING_WARNING",
    "GridSolver",
    "GridMindAgent",
    "GroundingValidation",
    "InspectionReport",
    "LLMClientError",
    "LimitProfile",
    "M1BenchmarkCheckResult",
    "M1BenchmarkResult",
    "M1BenchmarkRunner",
    "M1BenchmarkScenario",
    "M1BenchmarkSuiteResult",
    "M1OracleComparison",
    "MEMORY_CONTEXT_CAVEAT",
    "NumericClaim",
    "BackendDefinition",
    "PandaPowerSolver",
    "PowerFlowError",
    "PromptBuildResult",
    "PromptContextHints",
    "REPORTABLE_TOOLS",
    "SolverDependencyError",
    "StudyMemoryRecord",
    "StudyMemoryStore",
    "ToolCall",
    "ToolCallPolicyDecision",
    "ToolDefinition",
    "ToolExecutionRecord",
    "ToolRegistry",
    "ToolRegistryError",
    "VLLMConfig",
    "VLLMOpenAIClient",
    "SteadyStateCIARunner",
    "Violation",
    "ViolationInspector",
    "build_chat_messages",
    "build_deterministic_report",
    "build_gridmind_prompt",
    "build_tool_observation",
    "default_experiment_scenarios",
    "default_m1_benchmark_scenarios",
    "detect_capacity_route",
    "detect_cia_readiness",
    "evaluate_expectations",
    "evaluate_m1_result",
    "extract_context_hints",
    "filter_scenarios",
    "filter_m1_scenarios",
    "find_numeric_claims",
    "handle_forced_capacity_routing",
    "has_grounding_credit",
    "parse_chat_completion_response",
    "parse_completion_response",
    "parse_openai_function_call",
    "parse_openai_tool_calls",
    "parse_tool_calls_from_text",
    "profile_from_name",
    "remove_tool_call_blocks",
    "report_text_or_original",
    "render_qwen_chatml",
    "run_m1_oracles",
    "select_relevant_memory",
    "strip_qwen_thinking",
    "summarize_capacity_result",
    "tool_result_message",
    "tool_observation_payload",
    "validate_tool_call_policy",
    "validate_grounding",
]
